version: "3.9"

networks:
    net:

services:

    nginx:
        container_name: nginx
        image: nginx
        restart: always
        ports:
            # - 9000:443
            - 9001:80
        networks:
            - net
        volumes:
            # - ./.docker/https/localhost.chained.crt:/etc/ssl/private/localhost.chained.crt:ro
            # - ./.docker/https/localhost.key:/etc/ssl/private/localhost.key:ro
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src/spa/dist/spa:/usr/share/nginx/html:ro
        # depends_on:
            # spm-accr-api-v1:
                # condition: service_healthy
            
